version: '3'

services:
  flask-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/judge/.env  # .env 파일을 여기에 추가
    volumes:
      - ./backend/key.json:/app/key.json  # 호스트 머신의 backend/key.json 파일을 컨테이너 내부의 /app/key.json으로 마운트
  node-app:
    build:
      context: ./deploy-fe
      dockerfile: Dockerfile
    ports:
      - "10208:10208"
    depends_on:
      - flask-app
